### ISSUE TITLE
hide BottomNavigatorsBar

### ISSUE THREAD

**Issue by sh4msi** [LucasAschenbach/advanced_navigator#1]
hi,
What should I do if I want to hide BottomNavigatorsBar on a specific page when using nested navigator?

**Comment by LucasAschenbach** [comment]
There are two ways you can do this. Lets assume you have a widget FullscreenView() for which the BottomNavigationBar should be hidden.

1. Add a callback for showing/hiding the BottomNavigationBar to the initState and dispose functions of your FullscreenView widget.

2. You can simply add a callback to the path/page generator function. Example:

```
AdvancedNavigator(
  paths: {
    '/': (_) {
      _showBottomNavigationBar();
      return [
        MaterialPage(key: 'home', child: HomeView()),
      ];
    },
    '/fullscreenView': (_) {
      _hideBottomNavigationBar();
      return [
        MaterialPage(key: 'fullsecreenView', child: FullscreenView()),
      ];
  }
)
```

Which method is better for your depends on your use case.
