### ISSUE TITLE
reset previous tab data

### ISSUE THREAD

**Issue by sh4msi** [LucasAschenbach/advanced_navigator#2]
hi,
whenever I switch between tabs, I need the previous tab to reset(initialize)
(in nested navigation)

**Comment by LucasAschenbach** [comment]
Your navigator with control over the tabs should replace the entire page stack with the new page. That way, every page will always be re-initialized:

```
AdvancedNavigator(
  paths: {
    '/': (_) => [
      MaterialPage(key: ValueKey('home'), child: HomeView()),
    ],
    '/tab1': (_) => [
      MaterialPage(key: ValueKey('tab1'), child: Tab1View()),
    ],
    '/tab2': (_) => [
      MaterialPage(key: ValueKey('tab2'), child: Tab2View()),
    ],
  },
  transitionDelegate: NoAnimationTransitionDelegate(),
)
```

**Comment by sh4msi** [comment]
Thanks. I want the stack to return to normal when I exit the current nested tab (BottomNavigationBar).
(When I enter a new (different) tab, the previous nested tab returns to its home page)

> Please write me a small example of nested navigation with advanced navigator

**Comment by LucasAschenbach** [comment]
I'm afraid, I'm not exactly sure what you mean. Could you please clarify what the routing in your app is supposed to look like.
