### ISSUE TITLE
required RouteInformationReportingType type not required

### ISSUE THREAD

**Issue by fredgrott** [LucasAschenbach/advanced_navigator#4]
In the route information provider file

{required RouteInformationReportingType type}) 

is no longer required on recent flutter beta and stable

Will add to this issue report if my workaround to remove mentions of that type requirement does not work.

**Comment by LucasAschenbach** [comment]
Thanks for the report!
You're right, the required keyword has been removed in the latest beta. I took a brief look at the [source code](https://github.com/flutter/flutter/blob/097d3313d8e2c7f901932d63e537c1acefb87800/packages/flutter/lib/src/widgets/router.dart#L1329); it seem like this change has not made it into a stable release yet. However, if you want you can make a pull request with your changes and I will merge it as soon as the change is applied to the stable branch.

**Comment by LucasAschenbach** [comment]
The API changes were now added to the stable branch with the Flutter 3 release. I've just published a new release compatible with the new API.

Thanks again for reporting the issue!
